project:
  type: website
  render: 
    - "*.qmd"
  output-dir: docs
  preview:
    port: 4200

website:
  title: "R Para Ciencia De Datos"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



